### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [ ]:
import numpy as np

vector = np.random.rand(10)
matrix =np.array([[11, 14, 17],
                  [20, 23, 26],
                  [29, 32, 35]])
print("Вектор:")
print(vector)
print(f"Розмір вектора: {vector.shape}\n")
print("Матриця:")
print(matrix)
print(f"Розмір матриці: {matrix.shape}\n")

Вектор:
[0.43630272 0.26465355 0.03452686 0.81368376 0.1369432  0.4791595
 0.25706891 0.48628437 0.007315   0.32244325]
Розмір вектора: (10,)

Матриця:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
Розмір матриці: (3, 3)




### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [ ]:
vector_res = np.round(vector + 10, 2)
matrix_res = matrix * 2
vector_sq = vector ** 2
print("додавання 10 та округлення:")
print(vector_res)
print("\nмноження матриці на 2:")
print(matrix_res)
print("\nквадрати значень:")
print(vector_sq)

додавання 10 та округлення:
[10.44 10.26 10.03 10.81 10.14 10.48 10.26 10.49 10.01 10.32]

множення матриці на 2:
[[22 28 34]
 [40 46 52]
 [58 64 70]]

квадрати значень:
[1.90360065e-01 7.00415014e-02 1.19210386e-03 6.62081262e-01
 1.87534401e-02 2.29593827e-01 6.60844248e-02 2.36472489e-01
 5.35091941e-05 1.03969652e-01]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [ ]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [ ]:
result_matrix = np.dot(B, A)
print("result_matrix:")
print(result_matrix)
result_C = np.dot(result_matrix, C)
print("Результат множення на вектор C:")
print(result_C)
result_D = np.dot(result_matrix, D)
print("Результат множення на матрицю D:")
print(result_D)

result_matrix:
[[0.7281 0.5202]
 [0.2034 0.2846]]
Результат множення на вектор C:
[[0.5202]
 [0.2846]]
Результат множення на матрицю D:
[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [ ]:
result_matrix_T = result_matrix.T
print("Транспонована result_matrix:")
print(result_matrix_T)

Транспонована result_matrix:
[[0.7281 0.2034]
 [0.5202 0.2846]]


In [ ]:
vector_T = vector.T
print("Транспонований vector:")
print(vector_T)

Транспонований vector:
[0.43630272 0.26465355 0.03452686 0.81368376 0.1369432  0.4791595
 0.25706891 0.48628437 0.007315   0.32244325]


Нічого не змінилося

In [ ]:
column_vector = np.expand_dims(vector, axis=1)
print("column_vector:")
print(column_vector)

column_vector:
[[0.43630272]
 [0.26465355]
 [0.03452686]
 [0.81368376]
 [0.1369432 ]
 [0.4791595 ]
 [0.25706891]
 [0.48628437]
 [0.007315  ]
 [0.32244325]]


column_vector тепер є двовимірною матрицею

In [12]:
column_vector_T = column_vector.T
print("Транспонований column_vector:")
print(column_vector_T)
print("розмірність:", column_vector_T.shape)

Транспонований column_vector:
[[0.43630272 0.26465355 0.03452686 0.81368376 0.1369432  0.4791595
  0.25706891 0.48628437 0.007315   0.32244325]]
розмірність: (1, 10)
